// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB55fUGWnXLhVxWC_MhFyLv6qwBHQSo_5M',
    appId: '1:424361993466:web:876627578bfd36c1a45543',
    messagingSenderId: '424361993466',
    projectId: 'fossa-648e4',
    authDomain: 'fossa-648e4.firebaseapp.com',
    storageBucket: 'fossa-648e4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9fBMdakTqj71B9rON49ahmmR1Pzolyf8',
    appId: '1:424361993466:android:a26c3250d7de7539a45543',
    messagingSenderId: '424361993466',
    projectId: 'fossa-648e4',
    storageBucket: 'fossa-648e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6fC1ZAHOjX3UM88V9DtEWRQ8B4GPBVo8',
    appId: '1:424361993466:ios:215ad22b4067f48fa45543',
    messagingSenderId: '424361993466',
    projectId: 'fossa-648e4',
    storageBucket: 'fossa-648e4.appspot.com',
    iosClientId: '424361993466-vn4peacl2i086macb6fqp0mdrsfsq2op.apps.googleusercontent.com',
    iosBundleId: 'com.example.fossaFrontend',
  );
}
